In [3]:
import numpy as np

In [8]:
arr = np.array((1,2,3,'a'))
arr

array(['1', '2', '3', 'a'], dtype='<U11')

In [18]:
lis = [1,2,3]
print(f"list+list: {lis+[4,5,6]}")

arr = np.array((1,2,3))
lst_arr = arr + [4,5,6]
print(f"arr + list: {lst_arr}")
print(f"type(list+array) = {type(lst_arr)}")

list+list: [1, 2, 3, 4, 5, 6]
arr + list: [5 7 9]
type(list+array) = <class 'numpy.ndarray'>


In [22]:
print(arr/2)
print(arr**2)
print(arr*5)
print(arr + [5])
try:
    arr + [1,2] #=> ValueError
except ValueError as e:
    print(e)

[0.5 1.  1.5]
[1 4 9]
[ 5 10 15]
[6 7 8]
operands could not be broadcast together with shapes (3,) (2,) 


In [32]:
print(np.tanh(arr))
print(np.cos(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))


[0.76159416 0.96402758 0.99505475]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [38]:
arr2 = np.array([4,5,6])
print(np.sum(arr2*arr))
print(arr2.dot(arr))
print(arr2 @ arr)

32
32
32


In [40]:
a,b = arr,arr2
cosangle = a@b/(np.linalg.norm(a)*np.linalg.norm(b))
angle_degree= np.rad2deg(np.arccos(cosangle))
degree_sign= u'\N{DEGREE SIGN}'
print(f"{angle_degree}{degree_sign}")

12.933154491899135°


In [45]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [49]:
print(arr[0][0])
print(arr[0,0])


1
1


In [51]:
arr[:,0]

array([1, 3])

In [58]:
print(f"inverse of arr: ")
print(np.linalg.inv(arr))
print("determinant of arr:")
print(np.linalg.det(arr))
print("arr Transpose:")
print(arr.T)
print("trace of a:")
print(np.trace(arr))


inverse of arr: 
[[-2.   1. ]
 [ 1.5 -0.5]]
determinant of arr:
-2.0000000000000004
arr Transpose:
[[1 3]
 [2 4]]
trace of a:
5


In [61]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr.dot(arr2)


array([[ 9, 12, 15],
       [19, 26, 33]])

In [63]:
# a^(-1)*a == I ?
np.linalg.inv(arr).dot(arr) == np.array([[1,0],[0,1]])

array([[False,  True],
       [False,  True]])

In [64]:
np.allclose(np.linalg.inv(arr).dot(arr) , np.array([[1,0],[0,1]]))

True

In [5]:
equations = np.array([[1,1],[1.5,4]])
solutions = np.array([2200,5050])
x_value = np.linalg.solve(equations,solutions)
print(f'x1 = {x_value[0]}, x2 = {x_value[1]}')

x1 = 1500.0, x2 = 700.0


In [4]:
arr_zeros = np.zeros((3,4))
arr_ones = np.ones((3,4))
arr_tens = arr_ones * 10
arr_identity = np.eye(3)
print('~~~ 3X4 matrix of zeros ~~~')
print(arr_zeros)
print('~~~ 3X4 matrix of ones ~~~')
print(arr_ones)
print('~~~ 3X4 matrix of tens ~~~')
print(arr_tens)
print('~~~ 3X3 Identity matrix ~~~')
print(arr_identity)


~~~ 3X4 matrix of zeros ~~~
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
~~~ 3X4 matrix of ones ~~~
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
~~~ 3X4 matrix of tens ~~~
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
~~~ 3X3 Identity matrix ~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:

print(f'~~~ random: {np.random.random()} ~~~')
print(f'~~~ randint(1,100): {np.random.randint(1,100)} ~~~')
print(f'~~~ randint(1,100 size=(3,3)): ~~~ \n{np.random.randint(1,100, size=(3,3))}')
print(f'~~~ choice = [2,3,5,7,11,13],size=(3,3) ~~~\n{np.random.choice([2,3,5,7,11,13], size=(3,3))}')

~~~ random: 0.0908651100249237 ~~~
~~~ randint(1,100): 35 ~~~
~~~ randint(1,100 size=(3,3)): ~~~ 
[[76 57 17]
 [99 48 20]
 [10 58 89]]
~~~ choice = [2,3,5,7,11,13],size=(3,3) ~~~
[[ 3 11 13]
 [ 7 13  3]
 [ 5 13  2]]


In [8]:
# Normal Distribution:
'''The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array: '''

normal_dis = np.random.normal(size=(3, 3))
print('~~~ normal distribution: ~~~')
print(normal_dis)
print("loc=0.5, scale=2, size=(3, 3):")
normal_dis = np.random.normal(loc=0.5, scale=2, size=(3, 3))
print(normal_dis)


~~~ normal distribution: ~~~
[[ 0.47696639 -1.23156084 -1.26405106]
 [-1.4285541  -0.41995324  0.17663182]
 [ 0.77133265 -0.89298416  1.33024965]]
loc=0.5, scale=2, size=(3, 3):
[[ 3.12470323  2.09586883 -3.00645513]
 [-0.48714311 -3.07864598  2.02905453]
 [ 3.11557001  2.39858333 -0.53279862]]


In [5]:

# Binomial Distribution
'''
Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

n - number of trials.

p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).

size - The shape of the returned array.
'''
binomial_dis = np.random.binomial(n=10, p=0.5, size=(3,3))
print('~~~ binomial distribution: ~~~')
print("n=10, p=0.5, size=(3,3):")
print(binomial_dis)

~~~ binomial distribution: ~~~
n=10, p=0.5, size=(3,3):
[[7 5 3]
 [4 4 6]
 [5 5 6]]


In [6]:
# Poisson Distribution
'''
Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time.
e.g. If someone eats twice a day what is probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurences e.g. 2 for above problem.

size - The shape of the returned array.

'''
poisson_dis = np.random.poisson(lam=2, size=(3,3))
print('~~~ poisson distribution: ~~~')
print("lam=2, size=(3,3):")
print(poisson_dis)

~~~ poisson distribution: ~~~
lam=2, size=(3,3):
[[2 2 3]
 [1 9 3]
 [2 3 1]]


In [7]:

# Uniform Distribution
''' 
Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.
'''

uniform_dis = np.random.uniform(size=(3, 3))
print('~~~ uniform distribution: ~~~')
print("size=(3,3):")
print(uniform_dis)


~~~ uniform distribution: ~~~
size=(3,3):
[[0.83884483 0.75664461 0.40702989]
 [0.97541392 0.56412935 0.84010256]
 [0.05350044 0.42409649 0.51254916]]


In [95]:
def my_timer(orig_func):
    import time
    def wrapper(*args, **kwargs):
        t1 = time.time()
        result = orig_func(*args, **kwargs)
        t2 = time.time() - t1
        print(f'{ orig_func.__name__} ran in: {t2} sec')
        return result
    return wrapper


In [103]:
@my_timer
def list_mult(mat_a,mat_b):
    mat_c = []
    for i in range(len(mat_a)):
        mat_c.append([])
        for j in range(len(mat_b[0])):
            sum_val = 0
            for k in range(len(mat_b)):
                sum_val+= mat_a[i][k]*mat_b[k][j]
            mat_c[i].append(sum_val)
    return mat_c


@my_timer           
def array_mult(mat_a,mat_b):
    return mat_a @ mat_b
    


In [108]:
mat_a = np.random.randint(-100,100,size=(3,3))
mat_b = np.random.randint(-100,100,size=(3,3))

lst_a = list(mat_a)
lst_b = list(mat_b)

print(list_mult(lst_a,lst_b))
print(array_mult(mat_a,mat_b))

list_mult ran in: 0.0 sec
[[-2378, 2542, -4336], [-513, -3004, 512], [-9547, -5279, 8996]]
array_mult ran in: 0.0 sec
[[-2378  2542 -4336]
 [ -513 -3004   512]
 [-9547 -5279  8996]]


In [113]:
mat_a = np.random.randint(-100,100,size=(100,100))
mat_b = np.random.randint(-100,100,size=(100,100))

lst_a = list(mat_a)
lst_b = list(mat_b)
list_mult(lst_a,lst_b)
array_mult(mat_a,mat_b)
print("So what is faster?")

list_mult ran in: 0.5760326385498047 sec
array_mult ran in: 0.002000093460083008 sec
So who is faster?
