In [2]:
import numpy as np

In [3]:
arr = np.array((1,2,3,'a'))
arr

array(['1', '2', '3', 'a'], dtype='<U11')

In [4]:
lis = [1,2,3]
print(f"list+list: {lis+[4,5,6]}")

arr = np.array((1,2,3))
lst_arr = arr + [4,5,6]
print(f"arr + list: {lst_arr}")
print(f"type(arr + list) = {type(lst_arr)}")

list+list: [1, 2, 3, 4, 5, 6]
arr + list: [5 7 9]
type(arr + list) = <class 'numpy.ndarray'>


In [5]:
print(arr/2)
print(arr**2)
print(arr*5)
print(arr + [5])
try:
    arr + [1,2] #=> ValueError
except ValueError as e:
    print(e)

[0.5 1.  1.5]
[1 4 9]
[ 5 10 15]
[6 7 8]
operands could not be broadcast together with shapes (3,) (2,) 


In [32]:
print(np.tanh(arr))
print(np.cos(arr))
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))

[0.76159416 0.96402758 0.99505475]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.84147098 0.90929743 0.14112001]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]


In [6]:
arr2 = np.array([4,5,6])
print(np.sum(arr2*arr))
print(arr2.dot(arr))
print(arr2 @ arr)

32
32
32


In [7]:
a,b = arr,arr2
cosangle = a@b/(np.linalg.norm(a)*np.linalg.norm(b))
angle_degree= np.rad2deg(np.arccos(cosangle))
degree_sign= u'\N{DEGREE SIGN}'
print(f"The angle between {a} and {b} is {angle_degree}{degree_sign}")

The angle between [1 2 3] and [4 5 6] is 12.933154491899135°


In [9]:
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [11]:
print(arr[0][0])   # Java style
print(arr[0,0])    # C# style

1
1


In [12]:
print("First column: ", arr[:,0])
print("Second column: ", arr[:,1])
print("First row: ", arr[0,:])
print("Second row: ", arr[1,:])

First column:  [1 3]
Second column:  [2 4]
First row:  [1 2]
Second row:  [3 4]


In [14]:
print("arr Transpose:")
print(arr.T)
print("trace of a:")
print(np.trace(arr))
print("determinant of arr:")
print(np.linalg.det(arr))
print(f"inverse of arr: ")
print(np.linalg.inv(arr))

arr Transpose:
[[1 3]
 [2 4]]
trace of a:
5
determinant of arr:
-2.0000000000000004
inverse of arr: 
[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr.dot(arr2))
print(arr @ arr2) # equivalent

[[ 9 12 15]
 [19 26 33]]
[[ 9 12 15]
 [19 26 33]]


In [16]:
# a^(-1)*a == I ?
np.linalg.inv(arr).dot(arr) == np.array([[1,0],[0,1]])

array([[False,  True],
       [False,  True]])

In [17]:
np.allclose(np.linalg.inv(arr).dot(arr), np.array([[1,0],[0,1]]))

True

### Solving linear equations

In [19]:
# A child buys ticket for 1.5 shekels. 
# An adult buys ticket for 4 shekels. 
# The total amount collected is 5050.
# The total number of people is 2200.
# How many children and adults entered the park?
left_hand_side = np.array([
    [1,1],
    [1.5,4]]
)
right_hand_side = np.array(
    [2200,         #  1*children + 1*adults = 2200
    5050]          #  1.5*children + 4*adults = 5050
)
solution = np.linalg.solve(left_hand_side,right_hand_side)
print(f'children = {solution[0]}, adults = {solution[1]}')

children = 1500.0, adults = 700.0


### Special matrices

In [21]:
print('~~~ 3X4 matrix of zeros ~~~')
arr_zeros = np.zeros((3,4))
print(arr_zeros)
print('~~~ 3X4 matrix of ones ~~~')
arr_ones = np.ones((3,4))
print(arr_ones)
print('~~~ 3X4 matrix of tens ~~~')
arr_tens = arr_ones * 10
print(arr_tens)
print('~~~ 3X3 Identity matrix (I) ~~~')
arr_identity = np.eye(3)
print(arr_identity)

~~~ 3X4 matrix of zeros ~~~
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
~~~ 3X4 matrix of ones ~~~
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
~~~ 3X4 matrix of tens ~~~
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
~~~ 3X3 Identity matrix (I) ~~~
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:

print(f'~~~ random: {np.random.random()} ~~~')
print(f'~~~ randint(1,100): {np.random.randint(1,100)} ~~~')
print(f'~~~ randint(1,100 size=(3,3)): ~~~ \n{np.random.randint(1,100, size=(3,3,3))}')
print(f'~~~ choice = [2,3,5,7,11,13],size=(3,3) ~~~\n{np.random.choice([2,3,5,7,11,13], size=(3,3))}')

~~~ random: 0.6597822927135752 ~~~
~~~ randint(1,100): 85 ~~~
~~~ randint(1,100 size=(3,3)): ~~~ 
[[[ 2 76 64]
  [33 76 44]
  [51 69 75]]

 [[40 98 81]
  [59  3 42]
  [21 98 25]]

 [[34 18 88]
  [60 38 41]
  [19 35 83]]]
~~~ choice = [2,3,5,7,11,13],size=(3,3) ~~~
[[ 3  5 13]
 [11  2 11]
 [11  5  3]]


In [23]:
# Normal Distribution:
'''The Normal Distribution is one of the most important distributions.

It is also called the Gaussian Distribution after the German mathematician Carl Friedrich Gauss.

It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc.

loc - (Mean) where the peak of the bell exists.

scale - (Standard Deviation) how flat the graph distribution should be.

size - The shape of the returned array: '''

normal_dis = np.random.normal(size=(3, 3))
print('~~~ normal distribution: ~~~')
print(normal_dis)
print("loc=0.5, scale=2, size=(3, 3):")
normal_dis = np.random.normal(loc=0.5, scale=2, size=(3, 3))
print(normal_dis)

~~~ normal distribution: ~~~
[[ 2.08196859  0.34340503 -0.08690251]
 [-0.92217282  0.72787392 -0.57018168]
 [ 0.78393856 -1.19412512  0.9783413 ]]
loc=0.5, scale=2, size=(3, 3):
[[ 0.68656986  1.03067228  1.47711426]
 [ 0.12257099  1.02966615  2.31685891]
 [ 4.16871517 -0.01443844 -0.22648197]]


In [24]:

# Binomial Distribution
'''
Binomial Distribution is a Discrete Distribution.

It describes the outcome of binary scenarios, e.g. toss of a coin, it will either be head or tails.

It has three parameters:

n - number of trials.

p - probability of occurence of each trial (e.g. for toss of a coin 0.5 each).

size - The shape of the returned array.
'''
binomial_dis = np.random.binomial(n=10, p=0.5, size=(3,3))
print('~~~ binomial distribution: ~~~')
print("n=10, p=0.5, size=(3,3):")
print(binomial_dis)

~~~ binomial distribution: ~~~
n=10, p=0.5, size=(3,3):
[[5 2 8]
 [4 4 8]
 [7 5 2]]


In [25]:
# Poisson Distribution
'''
Poisson Distribution is a Discrete Distribution.

It estimates how many times an event can happen in a specified time.
e.g. If someone eats twice a day what is probability he will eat thrice?

It has two parameters:

lam - rate or known number of occurences e.g. 2 for above problem.

size - The shape of the returned array.

'''
poisson_dis = np.random.poisson(lam=2, size=(3,3))
print('~~~ poisson distribution: ~~~')
print("lam=2, size=(3,3):")
print(poisson_dis)

~~~ poisson distribution: ~~~
lam=2, size=(3,3):
[[2 2 0]
 [0 1 2]
 [3 2 3]]


In [26]:

# Uniform Distribution
''' 
Used to describe probability where every event has equal chances of occuring.

E.g. Generation of random numbers.

It has three parameters:

a - lower bound - default 0 .0.

b - upper bound - default 1.0.

size - The shape of the returned array.
'''

uniform_dis = np.random.uniform(size=(3, 3))
print('~~~ uniform distribution: ~~~')
print("size=(3,3):")
print(uniform_dis)


~~~ uniform distribution: ~~~
size=(3,3):
[[0.45887338 0.99730941 0.88456816]
 [0.719459   0.82616016 0.91117141]
 [0.184633   0.01771894 0.82059126]]


### Performance test - which array multiplication method is faster?

In [27]:
def my_timer(orig_func):
    import time
    def wrapper(*args, **kwargs):
        t1 = time.time()
        result = orig_func(*args, **kwargs)
        t2 = time.time() - t1
        print(f'{ orig_func.__name__} ran in: {t2} sec')
        return result
    return wrapper


In [28]:
@my_timer
def list_mult(mat_a,mat_b):
    mat_c = []
    for i in range(len(mat_a)):
        mat_c.append([])
        for j in range(len(mat_b[0])):
            sum_val = 0
            for k in range(len(mat_b)):
                sum_val+= mat_a[i][k]*mat_b[k][j]
            mat_c[i].append(sum_val)
    return mat_c


@my_timer           
def array_mult(mat_a,mat_b):
    return mat_a @ mat_b

In [29]:
mat_a = np.random.randint(-100,100,size=(3,3))
mat_b = np.random.randint(-100,100,size=(3,3))

lst_a = list(mat_a)
lst_b = list(mat_b)

print(list_mult(lst_a,lst_b))
print(array_mult(mat_a,mat_b))

list_mult ran in: 0.0 sec
[[1875, 2746, 2296], [-182, -3944, 2024], [-1628, -2594, -5987]]
array_mult ran in: 0.0 sec
[[ 1875  2746  2296]
 [ -182 -3944  2024]
 [-1628 -2594 -5987]]


In [33]:
mat_a = np.random.randint(-100,100,size=(200,200))
mat_b = np.random.randint(-100,100,size=(200,200))

lst_a = list(mat_a)
lst_b = list(mat_b)
list_mult(lst_a,lst_b)
array_mult(mat_a,mat_b)
print("So what is faster?")

list_mult ran in: 8.037827730178833 sec
array_mult ran in: 0.03708362579345703 sec
So what is faster?
